/*
** EPITECH PROJECT, 2026
** arcade
** File description:
** pacman map
*/

#pragma once

#include "pacman.hpp"

inline std::vector<std::vector<type>> FALLBACK_MAP() {
  return {
      {type::WALL, type::WALL, type::WALL, type::WALL, type::WALL, type::WALL,
       type::WALL, type::WALL, type::WALL, type::WALL, type::WALL, type::WALL,
       type::WALL, type::WALL, type::WALL, type::WALL, type::WALL, type::WALL,
       type::WALL, type::WALL, type::WALL, type::WALL, type::WALL, type::WALL,
       type::WALL, type::WALL, type::WALL, type::WALL},
      {type::WALL,   type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::WALL,   type::WALL,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::WALL},
      {type::WALL,   type::PACGUM, type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::PACGUM, type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::WALL,   type::PACGUM, type::WALL, type::WALL,
       type::PACGUM, type::WALL,   type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::PACGUM, type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::PACGUM, type::WALL},
      {type::WALL,   type::PACGUM,      type::SUPERPACGUM, type::PACGUM,
       type::PACGUM, type::WALL,        type::PACGUM,      type::WALL,
       type::EMPTY,  type::EMPTY,       type::EMPTY,       type::WALL,
       type::PACGUM, type::WALL,        type::WALL,        type::PACGUM,
       type::WALL,   type::EMPTY,       type::EMPTY,       type::EMPTY,
       type::WALL,   type::PACGUM,      type::WALL,        type::PACGUM,
       type::PACGUM, type::SUPERPACGUM, type::PACGUM,      type::WALL},
      {type::WALL,   type::PACGUM, type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::PACGUM, type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::WALL,   type::PACGUM, type::WALL, type::WALL,
       type::PACGUM, type::WALL,   type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::PACGUM, type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::PACGUM, type::WALL},
      {type::WALL,   type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::WALL},
      {type::WALL, type::PACGUM, type::WALL, type::WALL,   type::WALL,
       type::WALL, type::PACGUM, type::WALL, type::WALL,   type::PACGUM,
       type::WALL, type::WALL,   type::WALL, type::WALL,   type::WALL,
       type::WALL, type::WALL,   type::WALL, type::PACGUM, type::WALL,
       type::WALL, type::PACGUM, type::WALL, type::WALL,   type::WALL,
       type::WALL, type::PACGUM, type::WALL},
      {type::WALL,   type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::WALL,   type::WALL,   type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::WALL,   type::WALL,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::WALL,
       type::WALL,   type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::WALL},
      {type::WALL,   type::WALL,   type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::PACGUM, type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::WALL,   type::PACGUM, type::WALL, type::WALL,
       type::PACGUM, type::WALL,   type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::PACGUM, type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::WALL,   type::WALL},
      {type::WALL,   type::WALL,   type::WALL,   type::WALL,   type::WALL,
       type::WALL,   type::PACGUM, type::WALL,   type::WALL,   type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::WALL,   type::WALL,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::WALL,
       type::WALL,   type::PACGUM, type::WALL,   type::WALL,   type::WALL,
       type::WALL,   type::WALL,   type::WALL},
      {type::WALL, type::WALL,   type::WALL, type::WALL,   type::WALL,
       type::WALL, type::PACGUM, type::WALL, type::WALL,   type::PACGUM,
       type::WALL, type::WALL,   type::WALL, type::WALL,   type::WALL,
       type::WALL, type::WALL,   type::WALL, type::PACGUM, type::WALL,
       type::WALL, type::PACGUM, type::WALL, type::WALL,   type::WALL,
       type::WALL, type::WALL,   type::WALL},
      {type::WALL,  type::WALL,   type::WALL,  type::WALL,   type::WALL,
       type::WALL,  type::PACGUM, type::WALL,  type::WALL,   type::PACGUM,
       type::WALL,  type::EMPTY,  type::EMPTY, type::EMPTY,  type::EMPTY,
       type::EMPTY, type::EMPTY,  type::WALL,  type::PACGUM, type::WALL,
       type::WALL,  type::PACGUM, type::WALL,  type::WALL,   type::WALL,
       type::WALL,  type::WALL,   type::WALL},
      {type::EMPTY,     type::EMPTY,      type::EMPTY,      type::EMPTY,
       type::EMPTY,     type::EMPTY,      type::EMPTY,      type::EMPTY,
       type::EMPTY,     type::EMPTY,      type::GHOST_DOOR, type::EMPTY,
       type::RED_GHOST, type::EMPTY,      type::EMPTY,      type::BLUE_GHOST,
       type::EMPTY,     type::GHOST_DOOR, type::PACGUM,     type::EMPTY,
       type::EMPTY,     type::EMPTY,      type::EMPTY,      type::EMPTY,
       type::EMPTY,     type::EMPTY,      type::EMPTY,      type::EMPTY},
      {type::WALL,       type::WALL,   type::WALL,   type::WALL,
       type::WALL,       type::WALL,   type::PACGUM, type::WALL,
       type::WALL,       type::PACGUM, type::WALL,   type::EMPTY,
       type::PINK_GHOST, type::EMPTY,  type::EMPTY,  type::ORANGE_GHOST,
       type::EMPTY,      type::WALL,   type::PACGUM, type::WALL,
       type::WALL,       type::PACGUM, type::WALL,   type::WALL,
       type::WALL,       type::WALL,   type::WALL,   type::WALL},
      {type::WALL, type::WALL,   type::WALL, type::WALL,   type::WALL,
       type::WALL, type::PACGUM, type::WALL, type::WALL,   type::PACGUM,
       type::WALL, type::WALL,   type::WALL, type::WALL,   type::WALL,
       type::WALL, type::WALL,   type::WALL, type::PACGUM, type::WALL,
       type::WALL, type::PACGUM, type::WALL, type::WALL,   type::WALL,
       type::WALL, type::WALL,   type::WALL},
      {type::WALL,   type::WALL,   type::WALL,   type::WALL,   type::WALL,
       type::WALL,   type::PACGUM, type::WALL,   type::WALL,   type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::WALL,   type::WALL,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::WALL,
       type::WALL,   type::PACGUM, type::WALL,   type::WALL,   type::WALL,
       type::WALL,   type::WALL,   type::WALL},
      {type::WALL, type::WALL,   type::WALL, type::WALL,   type::WALL,
       type::WALL, type::PACGUM, type::WALL, type::WALL,   type::PACGUM,
       type::WALL, type::WALL,   type::WALL, type::WALL,   type::WALL,
       type::WALL, type::WALL,   type::WALL, type::PACGUM, type::WALL,
       type::WALL, type::PACGUM, type::WALL, type::WALL,   type::WALL,
       type::WALL, type::WALL,   type::WALL},
      {type::WALL,   type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::WALL,   type::WALL,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::WALL},
      {type::WALL,   type::PACGUM, type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::PACGUM, type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::WALL,   type::PACGUM, type::WALL, type::WALL,
       type::PACGUM, type::WALL,   type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::PACGUM, type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::PACGUM, type::WALL},
      {type::WALL,   type::PACGUM,      type::SUPERPACGUM, type::PACGUM,
       type::PACGUM, type::WALL,        type::PACGUM,      type::WALL,
       type::WALL,   type::WALL,        type::WALL,        type::WALL,
       type::PACGUM, type::WALL,        type::WALL,        type::PACGUM,
       type::WALL,   type::WALL,        type::WALL,        type::WALL,
       type::WALL,   type::PACGUM,      type::WALL,        type::PACGUM,
       type::PACGUM, type::SUPERPACGUM, type::PACGUM,      type::WALL},
      {type::WALL,   type::PACGUM, type::WALL,   type::WALL,   type::PACGUM,
       type::WALL,   type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACMAN, type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::WALL,   type::PACGUM, type::WALL,
       type::WALL,   type::PACGUM, type::WALL},
      {type::WALL,   type::WALL, type::WALL,   type::WALL,   type::PACGUM,
       type::WALL,   type::WALL, type::PACGUM, type::WALL,   type::WALL,
       type::PACGUM, type::WALL, type::WALL,   type::WALL,   type::WALL,
       type::WALL,   type::WALL, type::PACGUM, type::WALL,   type::WALL,
       type::PACGUM, type::WALL, type::WALL,   type::PACGUM, type::WALL,
       type::WALL,   type::WALL, type::WALL},
      {type::WALL,   type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::WALL,   type::WALL,
       type::PACGUM, type::PACGUM, type::PACGUM, type::WALL,   type::WALL,
       type::PACGUM, type::PACGUM, type::PACGUM, type::WALL,   type::WALL,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::WALL},
      {type::WALL,   type::PACGUM, type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::WALL,   type::WALL,   type::WALL, type::WALL,
       type::PACGUM, type::WALL,   type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::WALL,   type::PACGUM, type::WALL, type::WALL,
       type::WALL,   type::WALL,   type::WALL,   type::WALL, type::WALL,
       type::WALL,   type::PACGUM, type::WALL},
      {type::WALL,   type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::FOOD,   type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::PACGUM, type::WALL,   type::WALL,
       type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::FOOD,   type::PACGUM, type::PACGUM, type::PACGUM, type::PACGUM,
       type::PACGUM, type::PACGUM, type::WALL},
      {type::WALL, type::WALL, type::WALL, type::WALL, type::WALL, type::WALL,
       type::WALL, type::WALL, type::WALL, type::WALL, type::WALL, type::WALL,
       type::WALL, type::WALL, type::WALL, type::WALL, type::WALL, type::WALL,
       type::WALL, type::WALL, type::WALL, type::WALL, type::WALL, type::WALL,
       type::WALL, type::WALL, type::WALL, type::WALL}};
}
