name: Lint and Format

on:
  push:
    branches:
      - "main"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y build-essential cmake

      - name: Build project
        run: cmake -S . -B build && cmake --build build --config Release

      - name: Run tests
        run: |
          ctest --output-on-failure

  clang-format:
    name: Check Formatting (clang-format)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install clang-format-20
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          echo "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-20 main" | sudo tee /etc/apt/sources.list.d/llvm-20.list
          sudo apt-get update -qq && sudo apt-get install -y clang-format-20

      - name: Check formatting
        run: |
          find src include -type f \( -name '*.cpp' -o -name '*.hpp' \) \
            | xargs clang-format-20 --dry-run --Werror

  push_to_mirror:
    name: Push to Mirror Repository
    runs-on: ubuntu-latest
    needs: [build, clang-format]
    if: ${{ github.event_name == 'push' }}

    env:
      MIRROR_URL: "git@github.com:EpitechPGE2-2025/G-OOP-400-NAN-4-1-arcade-8.git"

    steps:
      - name: Check if repository is a mirror
        id: is_mirror_repo
        run: |
          REPO_PATH=$(echo "${{ github.repositoryUrl }}" | sed -E 's|^git://github.com/(.+)\.git$|\1|')
          MIRROR_PATH=$(echo "${{ env.MIRROR_URL }}" | sed -E 's|^git@github.com:(.+)\.git$|\1|')

          if [[ "$REPO_PATH" == "$MIRROR_PATH" ]]; then
            echo "is_mirror=true" >> $GITHUB_OUTPUT
          else
            echo "is_mirror=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        if: ${{ steps.is_mirror_repo.outputs.is_mirror == 'false' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror
        if: ${{ steps.is_mirror_repo.outputs.is_mirror == 'false' }}
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
